name: Build
on: push
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          target: Android64
      - uses: actions/upload-artifact@v4
        with:
          name: macro-recorder-android
          path: ${{ steps.build.outputs.build-output }}
